language: crystal

before_install:
  - curl -fsSL https://download.opensuse.org/repositories/devel:languages:crystal/Debian_10/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/crystal.gpg > /dev/null
  - echo "deb http://download.opensuse.org/repositories/devel:/languages:/crystal/Debian_10/ /" | sudo tee /etc/apt/sources.list.d/crystal.list
  - sudo apt-get update
  - sudo apt-get install -y crystal

crystal:
  - latest
  - nightly

script:
  - crystal spec
  - crystal tool format --check
